<?php
$section = "home";
include_once("header.php");
?>
<p>What do we do?  Everything.  And we do it well.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt eros commodo purus tristique placerat semper est imperdiet. Aenean fringilla sollicitudin eros, in vulputate felis venenatis et. Nunc eget lacus nulla, in euismod enim. Ut leo nibh, tempus et elementum porta, mattis quis elit. Praesent et neque sit amet nisi pellentesque semper. Pellentesque tristique lacus est. Integer porta feugiat nulla a lacinia. In convallis, tortor at sagittis eleifend, est turpis vehicula neque, ut consequat lorem odio vitae urna. Vestibulum nisl erat, lobortis eu tincidunt at, commodo eu nisl. Maecenas imperdiet mollis justo quis faucibus. Nam tempus turpis ut nisi elementum sagittis. Integer bibendum eros in metus tempor vitae fringilla risus rutrum. Ut iaculis aliquam mi eget auctor. Nulla lorem dolor, fringilla in aliquam eu, tincidunt bibendum nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed dignissim pretium tincidunt.</p>
<p>Aenean a ante enim. Curabitur eu nibh vitae massa pharetra gravida vitae eu nulla. Nulla viverra tellus et eros pharetra cursus tincidunt arcu aliquam. Nunc erat felis, sollicitudin rhoncus ullamcorper quis, tristique nec tortor. Mauris est leo, tempus in suscipit eget, mollis in arcu. Integer pharetra, tortor lobortis dignissim lobortis, eros tellus faucibus mi, vitae egestas felis orci eu magna. Donec rhoncus diam sed arcu facilisis iaculis. Quisque sapien urna, lacinia eu consectetur et, lacinia et diam. Aliquam dignissim mi non arcu ultricies accumsan. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec dignissim ligula vel lectus tincidunt id consequat ipsum convallis. Integer in velit aliquam purus commodo volutpat.</p>
<p>Mauris mattis tincidunt laoreet. Integer varius malesuada nulla, non porttitor nunc gravida ac. Etiam facilisis erat vel metus lobortis ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam malesuada nibh eu leo porta mattis. Nulla facilisi. Vivamus vulputate quam eget neque auctor fermentum. Cras aliquet volutpat nibh, quis rutrum eros rutrum et. Pellentesque fringilla leo non nisi porttitor bibendum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas ac dui et leo commodo adipiscing. Sed ut lacus erat, sit amet auctor justo. Praesent eu enim arcu, at tincidunt purus. Sed arcu nunc, aliquam sed interdum id, feugiat vitae tortor. Sed varius massa non nisl hendrerit ut placerat quam adipiscing.</p>
<p>Phasellus fringilla, tellus at bibendum pellentesque, odio justo hendrerit orci, et fermentum mauris tortor in nunc. Aliquam non nibh augue. Nullam fermentum faucibus sapien nec vulputate. Fusce euismod, eros vulputate elementum fermentum, sem magna pellentesque nunc, eu rhoncus urna orci vitae dui. Duis adipiscing viverra sapien aliquam convallis. Vivamus sollicitudin elit non eros convallis non sollicitudin nisl tristique. Maecenas vel molestie magna. Nunc laoreet porta ipsum aliquet congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer vitae nulla orci. Ut eu lorem risus, id tempus turpis. Vestibulum in nunc arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus tristique nisl et sapien tincidunt ac vestibulum dui sagittis. Curabitur mauris lectus, aliquet vitae iaculis non, commodo id ante. Morbi lorem nisl, pulvinar a aliquet cursus, pellentesque a sapien. Curabitur ac mauris quam, eu tincidunt diam. Fusce fringilla elementum risus, ac fermentum mi dapibus vel. Nullam rhoncus interdum mauris, ac dictum orci ornare in. Donec nunc tortor, consequat eu scelerisque non, pulvinar id libero.</p>
<p>Phasellus tempor neque sed lorem iaculis vehicula. Aenean urna nulla, pretium ut lacinia nec, ultrices vel libero. Duis aliquet arcu adipiscing erat egestas venenatis. Sed lacinia suscipit tellus, non vulputate justo tempus sit amet. Cras vitae metus non sapien imperdiet pharetra. Duis suscipit varius leo, eu accumsan velit luctus nec. Cras malesuada molestie fermentum. Donec eu nisl ac dui sagittis rutrum at vel nisl. Phasellus luctus, eros nec bibendum placerat, mi turpis molestie nisl, non fermentum nunc arcu elementum ligula. Sed bibendum rutrum orci, vitae vulputate nunc dictum in.</p>
<p id="cred"></p>
<!-- ADD THE "r." prefix to your image extension for any responsive images -->
<!-- <img src="sample-content/running-sml.jpg?full=sample-content/running-lrg.jpg" /> -->
<?php
include_once("footer.php");
?>